### ISSUE TITLE
Need permission to push library

### ISSUE THREAD

**Issue by bstillitano** [thumbmarkjs/thumbmark-swift#1]
Hey @ilkkapeltola,

I'm trying to push up some code to the repo however I don't have access. Getting the following error:

```
git --no-optional-locks -c color.branch=false -c color.diff=false -c color.status=false -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags --set-upstream origin refs/heads/main:refs/heads/main 
Pushing to github.com:thumbmarkjs/thumbmark-swift
ERROR: Permission to thumbmarkjs/thumbmark-swift.git denied to bstillitano.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'll also need my perms to be updated for the kotlin repo please.

**Comment by ilkkapeltola** [comment]
You need to accept the invitation to the repository. The invitation had expired. Please check your notifications. I've sent a new invite and will do the same for Kotlin too. @bstillitano bstillitano
